# .github/workflows/main_sparcollection-azfunc.yml
name: Build & deploy Python Azure Functions (ZIP)

on:
  push:
    branches: [ main ]
    paths:
      - 'azure_functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure_functions'
  PYTHON_VERSION: '3.10'
  FUNCAPP_NAME: 'sparcollection-azfuncy1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r ${AZURE_FUNCTIONAPP_PACKAGE_PATH}/requirements.txt

      - name: Zip Functions
        run: |
          cd ${AZURE_FUNCTIONAPP_PACKAGE_PATH}
          zip -qr ../azure_functions-release.zip .
          cd -

      - uses: actions/upload-artifact@v4
        with:
          name: functions-zip
          path: azure_functions-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: functions-zip
          path: .

      - name: Deploy zip to Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FUNCAPP_NAME }}
          slot-name: Production
          package: azure_functions-release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FUNCTIONS }}
